### ISSUE TITLE
Desktop KNG should have a resizeable window

### ISSUE THREAD

**Issue by Aleoami** [aspectron/kaspa-ng#21] opened 2024-06-14 12:31 UTC
Desktop KNG currently only supports maximizing the window, fullscreening it, and having it some default size. At least for me, on Windows 10. Should be freely resizable I believe.
![image](https://github.com/aspectron/kaspa-ng/assets/14896367/b98bdcd7-5443-4a86-b6e2-3fb6e33a28f7)

**Comment by aspect** [comment] 2024-06-14 12:40
Yeah, I am aware of the problem, it’s caused by the custom frame, but I can’t replicate it on my w11 machine as it resizes. I’ll try to take a look again this weekend, perhaps this is somehow screen resolution related. (there is a frame and it’s resizable but it looks like on some machines it is not. Perhaps increasing thickness of the frame to 2 pixels will solve this). I am also planning to add —noframe flag and a settings option to disable a custom frame.

Can you hop on Discord #help-kaspa-ng and ping @aspect .. as I am unable to replicate this it would be helpful if you could help test a build I make on your end.

**Comment by aspect** [comment] 2024-09-13 17:26
Upcoming 0.3.0 has an option in the Settings allowing to toggle window frame on and off (i.e. allowing it to be resizable). This setting is needed for Windows platform only as the custom frame works properly on MacOS and Linux.

Once the issue is resolved in dependencies custom frame will also work properly. In the meantime the toggle in settings can be used to enable the regular window frame.

**Closed by aspect** 2024-09-13 17:26 UTC
